name: LaTeX build
on: push
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install latexmk
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            main.tex
      - run: latexmk -pdf main.tex
      - uses: actions/upload-artifact@v6
        with:
          path: main.pdf
          if-no-files-found: error
