name: LaTeX build
on:
  push
  workflow_dispatch
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            main.tex
      - run: latexmk -pdf main.tex
      - uses: actions/upload-artifact@v6
        with:
          path: main.pdf
          if-no-files-found: error
